apiVersion: v1
kind: Secret
metadata:
  name: &microservice_name&-secret
  namespace: &namespace& # por favor colocar siempre el nombre del namespace definido en 'namespace.yml'
type: Opaque
stringData:
  # en 'data' se debe colocar cada archivo que se va llevar como configuracion al configmap
  application.yml: |
    server:
      host: localhost
      port: &containerPort&
      compression:
        enabled: true
        mime-types: application/json
        min-response-size: 2048
    spring:
      application:
        name: &microservice_name&
      datasource: # JDBC solo para liquibase
        host: &postgresql_host&
        port: &postgresql_port&
        database: &postgresql_database&
        schema: &postgresql_schema&
        username: &postgresql_username&
        password: &postgresql_password&
        driver-class-name: org.postgresql.Driver
      liquibase:
        enabled: true
        change-log: classpath:db/db.changelog-master.yaml
    adapters:
      r2dbc:
        host: &postgresql_host&
        port: &postgresql_port&
        database: &postgresql_database&
        username: &postgresql_username&
        password: &postgresql_password&
        schema: &postgresql_schema&
        other-schemas:
          payments: &postgresql_payment_schema&
        chunks: &postgresql_max_chunks&
      webclients:
        payments:
          url: &payments_microservice_calendar_endpoint&
        parameters:
          uri: &parameters_liquidation_uri&
          connection-time-out: &parameters_liquidation_connection_time_out&
          read-timeout: &parameters_liquidation_read_time_out&
          write-timeout: &parameters_liquidation_write_time_out&
        host: &base_endpoint_host&
    entrypoint:
      sqs:
        region: &queue_region&
        endpoint: &queue_endpoint&
        queue-url: &queue_url&
        wait-time-seconds: &queue_wait_time_seconds&
        visibility-timeout-seconds: &queue_visibility_timeout_seconds&
        max-number-of-messages: &queue_max_number_of_messages&
        number-of-threads: &queue_number_of_threads&
    
